{
 "title": "Uponor KM6",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Heizen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Ventil WoZi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_in_demand" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "Ventil Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_in_demand" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "Ventil Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_in_demand" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Fehler",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "avg temp low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_average_temp_low" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Allgemein" }
     ]
    },
    {
     "alias": "remote access",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_remote_access_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Allgemein" }
     ]
    },
    {
     "alias": "device lost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_device_lost_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Allgemein" }
     ]
    },
    {
     "alias": "tech WoZi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_technical_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "tech Kü",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_technical_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "tech Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_technical_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    },
    {
     "alias": "rf WoZi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rf_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "rf Kü",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rf_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "rf Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rf_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    },
    {
     "alias": "batt WoZi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_battery_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "batt Kü",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_battery_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "batt Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_battery_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Humidity",
   "type": "stat",
   "description": "Luftfeuchtigkeit in allen 3 Räumen",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rh_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rh_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rh_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Aussen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aussentemp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chalet",
     "select": [
      [
       { "params": [ "system_L_ambient" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vorlauf",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Vorlauf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chalet",
     "select": [
      [
       { "params": [ "hk1_L_flowtemp_set" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Modus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HomeAway",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_forced_eco_mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Allgemein" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": {
    "content": "<img src=\"https://www.uponor.de/-/media/uponor-internet/logos/uponor-logo.svg?la=en&amp;hash=6B1C99DFFE95B2C5EA42EA0827EC21E6C765E8A4\" alt=\"UPONOR\" />\n"
   }
  },
  {
   "title": "Heizanteil der Räume",
   "type": "piechart",
   "description": "welcher Raum heizt wieviel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WoZi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_utilization_factor_24h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_utilization_factor_24h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_utilization_factor_24h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Ist-Temp",
   "type": "stat",
   "description": "Gästevorgaben",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Differenz",
   "type": "stat",
   "description": "Gästevorgaben",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT (last(\"GS_room_temperature\")-last(\"GS_room_setpoint\")) FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'GS_Studio-WoZi') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Isttemp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GartenStudio" }
     ]
    },
    {
     "alias": "Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT (last(\"GS_room_temperature\")-last(\"GS_room_setpoint\")) FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'GS_Studio-Kueche') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Isttemp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "Studio-Kueche" }
     ]
    },
    {
     "alias": "Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT (last(\"GS_room_temperature\")-last(\"GS_room_setpoint\")) FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'GS_Studio-Bad') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Isttemp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Soll-Temp",
   "type": "stat",
   "description": "Gästevorgaben",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_setpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_setpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_setpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Raum-Stammdaten",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gartenstudio Wohnzimmer",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Room-name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_room_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "min-floortemp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_min_floor_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "max-floortemp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_max_floor_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "min-SetPoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_min_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "max-SetPoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_max_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "eco-offset",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_eco_offset" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "eco-mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_eco_profile_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "D-Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_average_room_temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "ch2thermometer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_ch_linked_to_th" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "rh-setpoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_rh_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "rh-deadzone",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_rh_deadzone" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "utilization_24h",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_utilization_factor_24h" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      }
     ]
    },
    {
     "title": "Gartenstudio Küche",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Room-name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_room_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "min-floortemp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_min_floor_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "max-floortemp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_max_floor_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "min-SetPoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_min_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "max-SetPoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_max_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
       ]
      },
      {
       "alias": "eco-offset",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_eco_offset" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "eco-mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_eco_profile_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "D-Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_average_room_temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "ch2thermometer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_ch_linked_to_th" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "rh-setpoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_rh_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "rh-deadzone",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_rh_deadzone" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      },
      {
       "alias": "utilization_24h",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_utilization_factor_24h" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
       ]
      }
     ]
    },
    {
     "title": "Gartenstudio Bad",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Room-name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_room_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "min-floortemp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_min_floor_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "max-floortemp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_max_floor_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "min-SetPoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_min_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "max-SetPoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_max_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "eco-offset",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_eco_offset" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "eco-mode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_eco_profile_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "D-Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_average_room_temperature" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "ch2thermometer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_ch_linked_to_th" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "rh-setpoint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_rh_setpoint" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "rh-deadzone",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_rh_deadzone" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      },
      {
       "alias": "utilization_24h",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uponor",
       "select": [
        [
         { "params": [ "GS_utilization_factor_24h" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Temperaturverläufe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Luftfeuchtigkeit im Bad",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "rH-set",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_rh_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Wohnzimmer",
   "type": "timeseries",
   "description": "Temperatur Soll-Ist im Vergleich",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "WoZi Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_setpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    },
    {
     "alias": "WoZi Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-WoZi" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Küche",
   "type": "timeseries",
   "description": "Temperatur Soll-Ist im Vergleich",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Küche Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_setpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    },
    {
     "alias": "Küche Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Kueche" }
     ]
    }
   ]
  },
  {
   "title": "Gartenstudio Bad",
   "type": "timeseries",
   "description": "Temperatur Soll-Ist im Vergleich",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Bad Soll",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_setpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    },
    {
     "alias": "Bad Ist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "GS_room_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "GS_Studio-Bad" }
     ]
    }
   ]
  }
 ]
}